### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by ProCompTEAM** [yoraze/PocketMine-MP#3]
![изображение](https://user-images.githubusercontent.com/24737193/68222435-11623100-fffc-11e9-82b5-7e9666a90505.png)

**Comment by yoraze** [comment]
Please download this submodule and move to src/pocketmine/resources/vanilla

https://github.com/yoraze/BedrockData/tree/master

**Comment by knzvgxd** [comment]
> Please download this submodule and move to src/pocketmine/resources/vanilla
> 
> https://github.com/yoraze/BedrockData/tree/master

it works, thanks
