### ISSUE TITLE
FloatingTextParticle error

### ISSUE THREAD

**Issue by knzvgxd** [yoraze/PocketMine-MP#4]
ArgumentCountError: "Too few arguments to function pocketmine\entity\Skin::__construct(), 2 passed in path/PocketMine-MP.phar/src/pocketmine/level/particle/FloatingTextParticle.php on line 99 and at least 4 expected" (EXCEPTION) in "src/pocketmine/entity/Skin" at line 67

**Comment by yoraze** [comment]
This fork pmmp has changes affecting BC. (Backwards Compatiblity)

There were really a lot of changes with the skins - I recommend reading the first commits in this repository.
